### ISSUE TITLE
Repeated CTD

### ISSUE THREAD

**Issue by Onfam** [SkyrimTogether/issues-game#123]
## Description

Skyrim Together runs fine alone, upon joining or hosting others I reliably freeze and CTD shortly after joining/creating the session.

NOTE: While actions such as other players forging, sitting on chairs, etc seem to potentially speed up the process, it still occurs while just standing around.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Load Savegame
3. Connect to other players (host/join)
4. Wait 30seconds-3minutes
5. Freeze & crash to desktop

## Reproduction rate

Every time my client connects to another player. (100%)

## Expected result

Freeze, then crash to desktop.

[crashlog.zip](https://github.com/SkyrimTogether/issues-game/files/2799582/crashlog.zip)

## Your environment

-Windows 7
-The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

None.

**Comment by Onfam** [comment]
Update: Created a new character in Skyrim Together (in case it was a corrupted save file), ran through Helgen alone, then attempted to join a game from Riverwood, same issue persists. Crashlog here:
[crashlog2.zip](https://github.com/SkyrimTogether/issues-game/files/2799614/crashlog2.zip)

**Comment by Pokang** [comment]
This is because you're running the mod through Windows 7, we found out the mod was being super crashy on this OS for some reason.
Your issue is easily fixable by following the instructions in this reddit post: https://www.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/
Closing the issue, feel free to come on Discord and complain about it if you're still having it after trying our fix.
