### ISSUE TITLE
Etched Tablets 

### ISSUE THREAD

**Issue by CoursePS** [SkyrimTogether/issues-game#151]
## Description

When walking up the staircase to High Hrothgar, there are _Etched Tablets_ along the way that you can read, if one player interacts with these, they pop up on the screens of other players too.

## Steps to reproduce

How to reproduce this issue:

1. Go with at least 2 players to Ivarstead.
2. Past the bridge to the mountain is an Etched Tablet.
3. Interact with it, the other player(s) near you will have it pop up on their screens as well.

## Reproduction rate

10/10 attempts.

## Expected result

Have it not show up on everyone's screen if one player interacts with it.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition Closed Beta

## Evidence (optional)

https://streamable.com/6wi8g
Excuse our gibberish, but Dutch is the superior language.

**Comment by f13rce** [comment]
I think it's the script within Skyrim that hardcoded this message to pop up if anyone interacts with that object, rather than just "the local player" (this means that a random NPC like Alvor could interact with it and you'd see the message as well).

I don't think we'll fix this, as this is Skyrim related rather than ST related. Nor do I think that we can find a flag for events like this. :/

P.S.: Dutch is indeed the superior language.
