### ISSUE TITLE
INFO [default] event=game_unload_resources"

### ISSUE THREAD

**Issue by ovkhan** [SkyrimTogether/issues-game#251]
Same error as https://www.reddit.com/r/SkyrimTogether/comments/ap7wl9/need_errorlog/
Error was fixed 17days ago, but i have the same problem.

Here is what i tested to fix it, but it's same method as one in Issue.
https://www.reddit.com/r/SkyrimTogether/comments/ap7wl9/need_errorlog/

**Comment by Pokang** [comment]
Firstly, I'll be closing this issue because you didn't use the template provided, and we really need the informations that it can give us.
Secondly, as I replied in that reddit post, this is a network problem that needs to be solved by the user. Copying what I posted on the Reddit post:

> The person who has the Failed to connect error definitely has something blocking the traffic between him and our server, if they have a firewall I'd suggest disabling it, same goes for any antivirus program. If you can't get it to work, try using a phone as a hotspot with 4G data for example, and let me know if that fixes it.

Let me know if you can get it to work.

**Comment by Pokang** [comment]
Hello, I just encountered someone who had this issue, and we managed to get it fixed by closing "Fraps" which they had running in the background.
Please don't use Fraps as it's very outdated and problematic with other programs.
@ovkhan Can you confirm me that you were using fraps?
Any other recording/overlay software could cause that issue, I'm still investigating it.
