### ISSUE TITLE
Auto Hide not working?

### ISSUE THREAD

**Issue by almanzarsaul** [SkyrimTogether/issues-game#254]
## Description

Autohide doesn't work whether I press autohide on or off
## Steps to reproduce

How to reproduce this issue:

1. Start the game
2. Invite and create session with friend
3. Press autohide off or autohide on and both autohide.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

N/A

## Reproduction rate

Everytime

## Expected result
Disable Auto Hide

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)
https://s2.gifyu.com/images/Auto-Hide-Not-Working.gif

## Final checks for the reporter

- [ x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ x] I made sure that I have applied the template for my bug report

**Comment by Dumbeldor** [comment]
Hi @almanzarsaul !

Thanks for this report. Sorry if I answer late.
It's not a bug. It's a perhaps clumsy way that I designed my ui. To make it simple, when you press "show" it disables the auto hide. Since you click on the option again, it turns it back on.
 
I'm thinking of a better way to do it. If you have any suggestions, don't hesitate to contact us ! :)

See ya

**Comment by Dumbeldor** [comment]
It's not a bug, it's a feature.
