### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Saeiko** [SkyrimTogether/issues-game#327]
## Description

When my friend launches his game via Harbor.exe, the game doesn't load and proceed to crash imediately after clicking the "PLAY" button with the error message down below (Evidence).

Related formIDs|
---------------|
None.

## Steps to reproduce

How to reproduce this issue:

1.Launch Harbor

2.Wait for the same update to finish

3.Click Play.
**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**. (Sorry I can't)

## Reproduction rate

100%

## Expected result

Launch the game without harbor crashing

## Your environment

* Game edition:
    * The Elder Scrolls V: Skyrim
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

https://image.noelshack.com/fichiers/2019/32/1/1565008874-capture.png

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Saeiko** [comment]
Sorry for bad English, it's not my main language.

**Comment by Dovachiin** [comment]
It’s an issue with Windows Defender, quick fix ripped straight from the discord:

**Fix for JavaScript error on Windows 10 due to Windows Defender**

• Go to Windows Security > Virus & Threat Protection > Manage Settings under "Virus & Threat Protection settings"  > Scroll down to Exclusions > Add or remove exclusions.

• Click "*+ Add an exclusion*".

• Choose "*Folder*".

• Navigate to the Harbor install folder and select it. Default location is `C:\Program Files (x86)\Tilted Phoques\Harbor`.

• Do the same for the Skyrim or Skyrim Special Edition install folder. Default location is `C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition`.

• Go to Windows Security > Virus & threat protection > Scroll down and click Manage ransomware protection under "Ransomware Protection" > Turn off Controlled folder access OR click on Block history, choose the recent "Protected folder access blocked" and choose *Allow on device" in Actions.

**Other Anti-Virus**

• Create similar exceptions with your anti-virus.

• If it still causes issues, try disabling it and then follow instructions for Windows Defender.

Should fix your issue.

**Comment by Pokang** [comment]
This was indeed the right fix, feel free to reopen if it still doesn't function normally.
Also, this is the wrong board, you should use the launcher issueboard.
