### ISSUE TITLE
Whiterun guards multiply and its crashing the players game.

### ISSUE THREAD

**Issue by LuciferMorningStarGod123** [SkyrimTogether/issues-game#332]
## Description
I've been running the server for  7-8 hours now. At the 8th hours, whiterun was getting laggy when I look at it and I went and check then it crash, I loaded up the game and join the server and was able to see about 30-40 guards standing outside of whiterun. I try to disable them but some of them have the same IDs so I cant disable them twice. This bug makes the mod unplayable right now because it's crashing me and another friend game whenever we enter a cave, fast travel, quicksaves. 

Related formIDs|
---------------|
Form IDs all for whiterun guards.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Enter a cave, quick save, fast travel
4.crash
5. disable whiterun guards
6. crash
![20190906224801_1](https://user-images.githubuserco
ntent.com/55009854/64469179-aed3de00-d0fb-11e9-95c8-ccfd1f414027.jpg)

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

It said git hub doesnt support that file type. So I put it in a zip.

[dmp files.zip](https://github.com/SkyrimTogether/issues-game/files/3586200/dmp.files.zip)

## Reproduction rate

How many times can you reproduce it?
Almost every time we enter a cave, quick saves, fast travel. Only one time that it doesn't crash
## Expected result

Describe your expected result.

## Your environment

Outside of white run, in front of the gate and on the drawbridge.

* Game edition (choose on which edition do you have problems):
   
     The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
 
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by LuciferMorningStarGod123** [comment]
https://user-images.githubusercontent.com/55009854/64469179-aed3de00-d0fb-11e9-95c8-ccfd1f414027.jpg

-Photo

**Comment by Pokang** [comment]
We are aware of this bug, but are not able to reproduce it internally just yet, guards just don't duplicate on our servers so we're unsure of the steps to take in order to make it happen.
That said, this one bug is at the top of our priority list right now, I will forward your report to the person in charge, thanks a lot.

**Comment by LuciferMorningStarGod123** [comment]
That’s good to hear that it’s a top priority. If you need anything that’s in my power to provide, I will provide it asap. Thank you

**Comment by f13rce** [comment]
This seems to be solved in the latest game save changed. Please re-open if the bug persists. :)

**Comment by MatasV** [comment]
Just reproduced it on TiltedPhoques/HEAD@13d3fd667 
There were double the guards that were standing at the "idle" positions in Whiterun and inside each other:
1) At the entrance
2) At the market
3) At the Dragonsreach, both near the entrance and next to the Jarl. 

I haven't had the pleasure of multiplying them further. If needed, I could try.

**Comment by f13rce** [comment]
Hi MatasV, thank you for the report.

Multiplication is to be expected in the current build for every LeveledActor, such as guards and bandits. Every player will synchronize their own guard, which causes X similar guards per X players.

The reason that we duplicate these is because most LeveledActors have some scripting reference to them. Deleting these LeveledActors will cause invalid references for other scripts which could cause instability (such as crashes).

Can you confirm that these guards are duplicated by our mod locally instead of them being spawned in by other players? If that is the case, then the bug is still alive. I believe this should not happen anymore every since we modified the LeveledActor synchronization, as well as modifying the saving process that caused the duplication.

In case you can confirm this, can you find a way to reproduce this so I can reopen this and address the issue? Thank you in advance!

**Comment by MatasV** [comment]
Hi, 

I hope to play it again it the upcoming weeks. I'll be sure to devote some time to test this issue out and generally keep an eye out for similar issues.

**Comment by MatasV** [comment]
Hi,

So it seems that the only time that the guards duplicate is when we are in the same cell. So this behavior correlates with that you've described.
